# Generated by Django 3.0.2 on 2020-04-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.TextField(help_text='Less than 100 characters', max_length=100),
        ),
    ]
