# Generated by Django 3.0.2 on 2020-04-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200402_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Less than 100 characters', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(help_text='* required. Describe the content of the content in this category', max_length=280, verbose_name='Description'),
        ),
    ]
