# Generated by Django 3.0.2 on 2020-04-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200402_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='Slug'),
        ),
    ]
